import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const itim = localFont({
  src: "./fonts/Itim-Regular.woff",
  variable: "--font-itim-sans",
});


export const metadata: Metadata = {
  title: "commissions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${itim.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
